name: arRVee
favicon: null
layout_spectrum: 0.5699629550799727
typography_spectrum: 0.9987739364150912
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#909598'
    - '#d1d5d6'
    - '#fefdfe'
    - '#a2c936'
  brandStrength: 0.5741840773262084
  lightness: 0.1412261740770191
  saturation: 0.6748534415382892
  rhythmicContrast: 0.5819019700866193
purpose: []
